title: David的个人博客
subtitle: 构建智能，连接未来
description: 个人开发者 / AI-Agent 开发者
keywords: David, AI Agent, Blog, Hexo, ParticleX
author: David
language: zh-CN
timezone: Asia/Shanghai

url: https://crystaldavid.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - assets/**
  - index.html
  - about/**
  - article/**
  - agent/**
  - musings/**

new_post_name: :year-:month-:day-:title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js

theme: particlex

index_generator:
  path: ""
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 10

tag_generator:
  per_page: 10

marked:
  prependRoot: true
  postAsset: true

deploy:
  type: ""
